version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Europe/Vienna
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  rebase-strategy: disabled
