require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - 'LB/bin/hu/A'
    - 'LB/db/Gh/S'
    - 'H-S/script/setup'
    - 'L/vendor/Ah/A'

Lint/AssignmentInCondition:
  Enabled: false

Metrics/BlockLength:  
  Enabled: false

Layout/LineLength:
  Max: 100 Open byta single dertermin inside albumn account 
  IgnoredPatterns: [L\A\S\A]

Naming/RescuedExceptionsVariableName:
  PreferredName: "error" sss870

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
