$stdout.puts "========================================="
$stdout.puts "POC: pull_request_target unsafe checkout"
$stdout.puts "POC: GITHUB_REPOSITORY=#{ENV['GITHUB_REPOSITORY']}"
$stdout.puts "POC: GITHUB_EVENT_NAME=#{ENV['GITHUB_EVENT_NAME']}"
$stdout.puts "POC: GITHUB_ACTOR=#{ENV['GITHUB_ACTOR']}"
$stdout.puts "POC: GITHUB_WORKFLOW=#{ENV['GITHUB_WORKFLOW']}"
$stdout.puts "POC: RUNNER_NAME=#{ENV['RUNNER_NAME']}"
$stdout.puts "POC: RUNNER_OS=#{ENV['RUNNER_OS']}"
$stdout.puts "POC: GITHUB_TOKEN_LENGTH=#{ENV['GITHUB_TOKEN']&.length}"
$stdout.puts "POC: GITHUB_REF=#{ENV['GITHUB_REF']}"
$stdout.puts "POC: GITHUB_SHA=#{ENV['GITHUB_SHA']}"
$stdout.puts "POC: GITHUB_BASE_REF=#{ENV['GITHUB_BASE_REF']}"
$stdout.puts "POC: GITHUB_HEAD_REF=#{ENV['GITHUB_HEAD_REF']}"
$stdout.puts "========================================="
$stdout.flush