name: houle1/khám phá/Github

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install bundler
      run: |
        gem install bundler:2.1.4
        bundle config path vendor/bundle
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Install gems
      if: steps.cache.outputs.cache-hit != 'true'
      run: bundle install --jobs 4 --retry 3
    - name: Build and test with Rake/Rubocop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bundle exec rake
        bundle exec rubocop --display-cop-names
