name: Build and Publish Jekyll for GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: 📂 checkout
        uses: actions/checkout@v6.0.2

      - name: 💎 setup ruby
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          bundler-cache: true
          cache-version: 0

      - name: 📄 setup pages
        id: pages
        uses: actions/configure-pages@v6.0.0

      - name: 🔨 install dependencies & build site
        uses: actions/jekyll-build-pages@44a6e6beabd48582f863aeeb6cb2151cc1716697 # v1.0.13

      - name: ⚡️ upload artifact
        uses: actions/upload-pages-artifact@v5.0.0

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: 🚀 deploy
        id: deployment
        uses: actions/deploy-pages@v5.0.0
