name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 steps:
    - uses: actions/checkout@v1.0.0
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1.0.0
      uses: ruby/setup-ruby@rosemariepahayo
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and catches installed gems automatically
    

